== Capturing SLF4J Logging

Sometimes the result of an operation ends up being a log message, or the lack thereof. This can be a tricky result to unravel, but if you are using the SLF4J logging API, you can use the `InMemoryLogAppender`, which is based on the Logback logging implementation (the primary implementation of the SLF4J API).

To capture the log events without a lot of complex mocking, all you need to do is inject your own `Appender` - simply put, the `Appender` implementations are what collects the log events and renders them in some usable format (e.g log files).

In order to test and verify logging events, you need to create an instance of the `InMemoryLogAppender` and configure it with the logged classes that you want it to capture the events of.

[source,java]
----
class SomeTest {

    private final InMemoryLogAppender appender = new InMemoryLogAppender(cfg -> {
        cfg.loggedClass(Alpha.class);
        cfg.loggedClass(Bravo.class);
    });
}
----

In order for the appender to be registered properly with the logging system, the `InMemoryLogAppender::attach()` method must be called once all of the logger configuration has been performed. When the testing is done, the `InMemoryLogAppender::detach()` method should be called to clean up the test logger configurations. These operations are best performed in the `@BeforeEach` and `@AfterEach` methods, such as (adding to the above example):

[source,java]
----
@BeforeEach void beforeEach() {
    appender.attach();
}

@AfterEach void afterEach() {
    appender.detach();
}
----

Then you can run your test target and examine the generated (collected) log events in the appender with the various provided accessor methods.

NOTE: There is also a JUnit 5 extension that makes using this even easier - see the <<LogAppenderExtension>> for details.

=== Matchers

A few Hamcrest matchers have been provided specifically for use with this log testing framework:

* The `LogLevelMatcher` matches criteria for the log level of the event.
* The `LogMessageMatcher` matches criteria for the log message string of the event.
* The `LogNameMatcher` matches criteria for the logger name for the event.


