== Hamcrest Matchers

The test-things library provides a collection of useful https://hamcrest.org/JavaHamcrest/[Hamcrest] matchers to aid in testing.

NOTE: Below are some of the provided matchers - see that Java Docs for a comprehensive list.

*Files.* The `FileMatcher` provides matchers for many commonly-used file-related properties.

[source,java]
----
assertThat(file, allOf(isFile(), fileExists(), isReadable()));
----

*Date.* The `ChronoLocalDateMatcher` supports the matching of date objects implementing the `ChronoLocalDate` interface, such as `LocalDate` instances.

[source,java]
----
assertThat(someDate, ChronoLocalDateMatcher.isAfter(otherDate));
----

*Date Time.** The `ChronoLocalDateTimeMatcher` supports the matching of date-time objects implementing the `ChronoLocalDateTime` interface, such as the `LocalDateTime` instances.

[source,java]
----
assertThat(someDateTime, ChronoLocalDateTimeMatcher.isBefore(otherDateTime));
----

*Date Operations.* The `TemporalMatcher` supports matching of various `Temporal` fields.

[source,java]
----
assertThat(someDate, TemporalMatcher.isAfternoon());
----

*Predicate Wrapper.* The `PredicateMatcher` wraps a `Predicate<T>` instance to allow it to be used as a Hamcrest matcher.

[source,java]
----
assertThat(something, PredicateMatcher.matchesPredicate(v -> v > 100));
----

*Byte Arrays.* The `ByteArrayMatcher` provides a set of matchers for `byte[]` arrays, which can be tricky in testing.

[source,java]
----
assertThat(bytes, ByteArrayMatcher.arrayStartsWith(someBytes));
----

*Atomics.* The `AtomicMatcher` provides some matchers for matching "atomic" objects.

[source,java]
----
assertThat(counter, AtomicMatcher.atomicIntIs(equalTo(42)));
----