= Test Things User Guide
Christopher J. Stehno
v0.0.1, January 2023
:toc: left
:toclevels: 4

== Introduction

Over the years I have written and collected various approaches to unit testing challenging code. This library is my
attempt to formalize these tools into a cohesive codebase and provide them for others to use.

*Test Things?* Is it a statement, as in "things for testing", or is it a command, telling you to "go forth and test"? It's
up to you.

WARNING: This is project is considered a BETA release at this point. I don't foresee any breaking changes at this point, but keep in mind that until a 1.0.0 release things are subject to change.

== Getting Started

The Test-Things artifacts are available via the Maven Central repository. Below are the dependency coordinates for Gradle and Maven.

For Gradle:

----
testImplementation 'io.github.cjstehno:test-things:0.1.0'
----

For Maven:

----
<dependency>
    <groupId>io.github.cjstehno</groupId>
    <artifactId>test-things</artifactId>
    <version>0.1.0</version>
    <scope>test</scope>
</dependency>
----

include::fixtures.adoc[]

include::junit_extensions.adoc[]

include::matchers.adoc[]

include::verifiers.adoc[]

include::injectors.adoc[]

include::randomizers.adoc[]

include::logging.adoc[]

include::serdes.adoc[]

== Other Useful Testing Libraries

*https://junit.org[JUnit 5].* The gold standard for Java unit testing frameworks - though if you are reading this, you probably already know that.

*http://cjstehno.github.io/ersatz[Ersatz Server].* A useful framework for testing HTTP client code against a real server with pre-determined responses and expectations. A sister project to this library.

*http://hamcrest.org[Hamcrest].* An expressive framework for assertion matchers - the matchers in test-things are based on this framework.

*http://www.awaitility.org/[Awaitility].* Library providing a means of testing asynchronous code in a stable and repeatable manor.

*https://mockito.org[Mockito].* A powerful mocking and stubbing library.

== Appendices

== A. Development Philosophy

As with my other project, the https://cjstehno.github.io/ersatz[Ersatz Server], I intend to keep this project as clean
and useful as possible, without holding on too tightly strict rules.

Being that this is a project used in writing unit tests, I don’t generally feel the need for strict backwards compatability as long as there is a simple upgrade path. That being said, if some change causes a major problem, I am not against cutting a new release with changes that make the transition easier.

== B. License

This project is licensed under the https://www.apache.org/licenses/LICENSE-2.0[Apache 2.0 License].

[source,text]
----
Copyright (C) 2023 Christopher J. Stehno

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
----